### PR TITLE
chore: use lerna

### LINKED ISSUE #12: dependencies to workspace packages should be updated to actual version before publishing
Now when installing `@sd-jwt/core` it will prompt you which version of the other `@sd-jwt` you want to install as it can't find a match for `workspace:*`

### PR DESCRIPTION
**Pull request by TimoGlastra**
Lerna seems to work well with pnpm.

It's only used for the publishing, and it required minimal changes to the setup. I committed the pnmp-lock.yaml as lerna will commit that when making updates, is there a specific reason it was ignored, as it's normal to commit the lock file to your repository.

Fixes #12

### CODE REVIEW

**Comment by berendsliedrecht** [comment]
> is there a specific reason it was ignored, as it's normal to commit the lock file to your repository.

Lock files should only be committed for binaries (or end-applications in general), but not for libraries. The main reason for that is to make sure the library works with the latest dependencies that are allowed will work (as those will be used by the binary).

**Review by berendsliedrecht — APPROVED** [review]
Is there a way to do this without committing the lock file? Otherwise it's okay, but I prefer not to.

**Comment by TimoGlastra** [comment]
I can look, but I'm curious why you wouldn't commit the lockfile?

It's the most anti-pattern you can think of probably 😅 I'm just really curious why.

https://pnpm.io/git

From PNPM docs:

> You should always commit the lockfile (pnpm-lock.yaml).

**Comment by berendsliedrecht** [comment]
> I can look, but I'm curious why you wouldn't commit the lockfile?
> 
> It's the most anti-pattern you can think of probably 😅 I'm just really curious why.
> 
> https://pnpm.io/git
> 
> From PNPM docs:
> 
> > You should always commit the lockfile (pnpm-lock.yaml).

I mainly got the pattern from Rust (https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control). I can see arguments for both, but if it is needed for Lerna it is all good.

**Comment by TimoGlastra** [comment]
Okay did some digging and lerna has hardcoded to add pnpm-lock to git, and git will error if you try to add a file that is ignored. 

I don't see a straightforward to hook into this (tried some custom scripts that add / remove from gitignore before/after, but that will make the working directroy dirty and then lerna will also error as it will commit the changes to the gitignore then)

**Comment by berendsliedrecht** [comment]
> will make the working directroy dirty and then lerna will also error as it will commit the changes to the gitign

Then I will merge it like this, thanks for checking!

**Pull request merged**
